//defines.h

#define WRITEBYTE(WORD,STARTBIT,BYTE) WORD=((WORD&(u32)~0xFF<<STARTBIT)|(BYTE<<STARTBIT))
#define WRITEBIT(WORD,BIT,BITVAL) WORD=((WORD&~(1<<BIT))|(BITVAL<<BIT))
#define WRITENIBBLE(WORD,STARTBIT,NIBBLE) WORD=((WORD&(u32)~0xF<<STARTBIT)|(NIBBLE<<STARTBIT))
#define READBIT(WORD,BIT) ((WORD>>BIT)&1)
#define READNIBBLE(WORD,SBIT) ((WORD>>SBIT)&0xF)
#define READWRITEBIT(WORD,DBIT,SBIT) WORD=((WORD&~(1<<DBIT))|(((WORD>>SBIT)&1)<<DBIT))
#define READWRITENIT2(DWORD,DBIT,SWORD,SBIT) DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))
